Changes to support Appcivist Integration
joausaga/social-ideation pull request #13
Opened 2017-09-12 15:19 UTC by MarceMMAD

- AppCivist Connector, callbacks, params, and urls added.
- Headers required from AppCivist Platform added to Social Ideation Requests.
- AppCivist auotmatic Session Key update added as a periodic tasks
- Bug fixes on AppCivist's Views and API client.

2017-09-14 16:28 UTC, joausaga requested changes

2017-09-14 16:28 UTC, joausaga commented on README.md
> +2. Create a virtual environment by running `virtualenv env`
@MarceMMAD creo que falta un paso intermedio aquí. Luego de crear el environment hay que activarlo `source active env` y después instalar las dependencias. Correcto?

2017-09-14 16:28 UTC, joausaga commented on README.md
>      If an error occurs during the installation, it might be because some of these resons:
Guarda con el inglés, es reasons no resons

2017-09-14 16:28 UTC, joausaga commented on README.md
> + 11. Add the following programs routes(rabbit, celery and celerybeat) at the *program section* of the supervisor configuration file (supervisord.conf).
Debe haber un espacio entre 'routes' y el '('

2017-09-14 16:28 UTC, joausaga commented on README.md
> + 2. If your are using IdeaScale, Create an IdeaScale Community. If you are using AppCivist create an Assembly with at least one member with administrator role, and at least with one campaign.
If **you** are using IdeaScale, **c**reate an IdeaScale Community

2017-09-14 16:28 UTC, joausaga commented on README.md
> + 2. If your are using IdeaScale, Create an IdeaScale Community. If you are using AppCivist create an Assembly with at least one member with administrator role, and at least with one campaign.
and at least one campaign (sin 'with')

2017-09-14 16:28 UTC, joausaga commented on README.md
> + 4. [Create a Facebook App](http://nodotcom.org/python-facebook-tutorial.html). OBS: This app need to be reviewed and approved by Facebook to ask for _**email**_, _**public_profile**_ and _**publish_
Yo reescribiría la observación así
Because the app requires .... permissions to work, it, first, has to be approved by Facebook.

2017-09-14 16:28 UTC, joausaga commented on README.md
> + 7. Go inside social ideation directory and load initial IdeaScale data `python manage.py loaddata ideascale_connector_data.json`. This will load both, IdeaScale and AppCivist connectors data.
No debería ser entonces "load initial IdeaScale **and AppCivist data by running**..."

2017-09-14 16:28 UTC, joausaga commented on README.md
> + 9. Hit the social ideation URL, i.e., http://www.social-ideation.com/admin, http://localhost:8000/admin. This will send you to the Administration Login page. Log in with the admin credentials.
This will **redirect** you to the ...

2017-09-14 16:28 UTC, joausaga commented on README.md
> + 17.  Create a social network app user (*Home->App->Social network app users->Add*) setting in the field access token the previously obtained access token in Step 15.
Esta instrucción no es clara

2017-09-14 16:28 UTC, joausaga commented on README.md
> + 18. Create a social network app community (*Home->App->Social network app communities->Add*) choosing **Group** as type and the social network app user created in Step 17 as the admin.
in **the** Step 17

2017-09-14 16:28 UTC, joausaga commented on README.md
> + 20. To start syncrhonization run the bash script called init_things.sh with the following command: ```bash init_sync.sh```. Be sure than the Django server it's up and running before running this com
called **init_sync.sh** no init_things.sh

2017-09-14 16:28 UTC, joausaga commented on README.md
> + 21. To stop synchronization run the bash script called stop_things.sh with the following command: ```bash stop_sync.sh```
idem comentario anterior

2017-09-14 16:28 UTC, joausaga commented on appcivist/serializers.py
> +        exclude = ('appcivist_id', 'appcivist_uuid', 'resource_space_id', 'forum_resource_space_id', 'admin_session_key', 'admin_email', 'admin_password', 'session_key_last_update', 'session_key_long
es muy larga la linea, no sigue las convenciones pep8 https://www.python.org/dev/peps/pep-0008/

2017-09-14 16:28 UTC, joausaga commented on appcivist/views.py
> +        idea = Idea(appcivist_id=idea_obj["contributionId"], appcivist_uuid=idea_obj["uuidAsString"] ,title=title, text=text,
Linea muy larga

2017-09-14 16:28 UTC, joausaga commented on appcivist/views.py
>          comment = Comment(appcivist_id=comment_obj["contributionId"], appcivist_uuid=comment_obj["uuidAsString"], text=comment_obj["text"],
linea muy larga

2017-09-14 16:28 UTC, joausaga commented on appcivist/views.py
> +            comment_details = {"status": "PUBLISHED", "title": request.data['text'][:10], "text": request.data["text"], "type": "DISCUSSION"}
linea muy larga

2017-09-14 16:28 UTC, joausaga commented on appcivist/views.py
> +            comment_details = {"status": "PUBLISHED", "title": request.data["text"][:10], "text": request.data["text"], "type": "COMMENT"}
linea muy larga

2017-09-14 16:28 UTC, joausaga commented on appcivist/serializers.py
> +        exclude = ('appcivist_id', 'user', 'parent_idea', 'parent_comment', 'sync', 'resource_space_id', 'forum_resource_space_id')
Linea muy larga

2017-09-14 16:28 UTC, joausaga commented on appcivist/views.py
> +from appcivist.serializers import AssemblySerializer, CampaignSerializer, AuthorSerializer, IdeaSerializer, CommentSerializer, FeedbackSerializer
linea muy larga

2017-09-14 16:28 UTC, joausaga commented on appcivist/views.py
> +            idea_obj = get_appcivist_data(assembly, 'get_idea_details', {'coid': idea_id, 'aid': assembly.appcivist_id})
linea muy larga

2017-09-14 16:28 UTC, joausaga commented on appcivist/views.py
> +        idea = Idea(appcivist_id=idea_obj["contributionId"], appcivist_uuid=idea_obj["uuidAsString"] ,title="", text=idea_obj["title"],
linea muy larga

2017-09-14 16:28 UTC, joausaga commented on appcivist/views.py
> +                    campaign=campaign_idea, url=url, user=author, sync=False, resource_space_id=idea_obj["resourceSpaceId"], forum_resource_space_id=idea_obj["forumResourceSpaceId"])
linea muy larga

2017-09-14 16:28 UTC, joausaga commented on appcivist/views.py
>              comment_obj = get_appcivist_data(assembly, 'get_comment_details', {'coid': comment_id, 'aid': assembly.appcivist_id})
linea muy larga

2017-09-14 16:28 UTC, joausaga commented on appcivist/views.py
>                            parent_type=parent_type, sync=False, resource_space_id=comment_obj["resourceSpaceId"], forum_resource_space_id=comment_obj["forumResourceSpaceId"])
linea muy larga

2017-09-14 16:28 UTC, joausaga commented on appcivist/views.py
>          feedback = Feedback(appcivist_id=feedback_obj["id"], value=feedback_value, datetime=feedback_dt, author=author, sync=False,
linea muy larga

2017-09-14 16:28 UTC, joausaga commented on appcivist/views.py
> +            idea_details = {"status": "PUBLISHED", "title": request.data["title"], "text": request.data["text"], "type": "IDEA", "campaigns":[request.data['campaign_id']]}
linea muy larga

2017-09-14 16:28 UTC, joausaga commented on appcivist/views.py
>              comment_details = {"status": "PUBLISHED", "text": request.data["text"], "type": "DISCUSSION", "campaigns":[request.data['campaign_id']]}
linea muy larga

2017-09-14 16:28 UTC, joausaga commented on appcivist/views.py
> +            return Response('Error: Idea with id {} does not exist'.format(idea_id), status=status.HTTP_400_BAD_REQUEST)
linea muy larga

2017-09-14 21:26 UTC, MarceMMAD commented
@joausaga ahi te hice los cambios

2017-09-18 14:28 UTC, joausaga approved these changes

2017-09-18 14:30 UTC, merged